# Generated by Django 5.1.3 on 2024-11-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_graph"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graph",
            name="author",
        ),
    ]
